version: '3'
services:

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=scrapy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    expose:
      - "5432"

  chumachenkosreality-web:
    build: .
    ports:
      - "5055:5055"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

#  adminer:
#    image: adminer
#    restart: always
#    expose:
#      - "5055"
