version: '3'
services:

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=scrapy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    expose:
      - "5432"

  chumachenkosreality-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db