version: '3'
services:

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=scrapy_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    expose:
      - "5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  chumachenkosreality-web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_ENV=development
    depends_on:
      - db